apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-nginx
  namespace: nginx
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx
      version: "15.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1
    service:
      type: ClusterIP
